services:

  backend:
    build: DeepHack-Backend
    ports:
      - 5000:5000
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000

  frontend:
    build: DeepHack-Frontend
    ports:
      - 8080:8080
    command: http-server dist